- request:
    url: ^/api/book$
    method: GET
    headers:
      content-type: application/json
  response:
    status: 200
    latency: 500
    headers:
      content-type: application/json
    file: flight.json
